### ISSUE TITLE
Comment:Step-Basic-Hooks-1: running server produces _noschema_ error

### ISSUE THREAD

**Issue by necmettin** [feathersjs/feathers-docs#678]
`> node ./examples/step/01/hooks/1` produces:

```
feathers-docs/node_modules/ajv/lib/ajv.js:94
    if (!v) throw new Error('no schema with key or ref "' + schemaKeyRef + '"');
            ^

Error: no schema with key or ref "http://json-schema.org/draft-04/schema#"
    at Ajv.validate (feathers-docs/node_modules/ajv/lib/ajv.js:94:19)
    at Ajv.validateSchema (feathers-docs/node_modules/ajv/lib/ajv.js:178:22)
    at Ajv._addSchema (feathers-docs/node_modules/ajv/lib/ajv.js:310:10)
    at Ajv.compile (feathers-docs/node_modules/ajv/lib/ajv.js:116:24)
    at exports.default (feathers-docs/node_modules/feathers-hooks-common/lib/services/validate-schema.js:21:22)
    at Function.user (feathers-docs/examples/step/01/hooks/1.js:43:7)
    at Function.configure (feathers-docs/node_modules/feathers/lib/application.js:138:8)
    at Function.services (feathers-docs/examples/step/01/hooks/1.js:28:8)
    at Function.configure (feathers-docs/node_modules/feathers/lib/application.js:138:8)
    at Object.<anonymous> (feathers-docs/examples/step/01/hooks/1.js:21:4)
```

**Comment by eddyystop** [comment]
I'm not getting an error on Ubuntu.

1. What system are you running on?
2. Try removing the line with `$schema: 'http://json-schema.org/draft-04/schema#',` as that's what its complaining about.
3. If (2) works, try reading that URL from the server using `fetch`.

Please let me what happens.

**Comment by eddyystop** [comment]
I've dug further into this. Could you have perhaps updated the dependencies to their latest versions? If so you'd be using ajv v5.1.5 instead of the 4.11.5 the example specifies.

With v5.1.5 you have to either
- change `http://json-schema.org/draft-04/schema` to `http://json-schema.org/draft-05/schema`, or
- explicitly add meta-schema to the validator instance: `ajv.addMetaSchema(require('ajv/lib/refs/json-schema-draft-04.json'));`

I've commented out the `$schema: 'http://json-schema.org/draft-04/schema#',` line as that works and may avoid future problems.

**Comment by necmettin** [comment]
Yes, I've updated the dependencies to their latest versions.

Thanks for the quick fix.
