### ISSUE TITLE
Issues with node modules running chat app

### ISSUE THREAD

**Issue by kuncevic** [feathersjs/feathers-docs#785]
I just cloned the repo and looking trough the `chat app`
Running yarn, then `npm start` giving me error:

```
> guide-chat-server@0.0.0 start c:\Projects\research\feathers-docs\examples\chat\server\finish
> node src/

module.js:472
    throw err;
    ^

Error: Cannot find module 'feathers-hooks-common/lib/populate'
    at Function.Module._resolveFilename (module.js:470:15)
    at Function.Module._load (module.js:418:25)
    at Module.require (module.js:498:17)
    at require (internal/module.js:20:19)
    at Object.<anonymous> (c:\Projects\research\feathers-docs\examples\chat\server\finish\node_modules\feathers-hooks\lib\hooks.js:13:17)
    at Module._compile (module.js:571:32)
    at Object.Module._extensions..js (module.js:580:10)
    at Module.load (module.js:488:32)
    at tryModuleLoad (module.js:447:12)
    at Function.Module._load (module.js:439:3)
```

Then removing the `node_modules`

Running `npm install` then `npm start` giving me another error:
```
c:\Projects\research\feathers-docs\examples\chat\server\finish>npm start

> guide-chat-server@0.0.0 start c:\Projects\research\feathers-docs\examples\chat\server\finish
> node src/

c:\Projects\research\feathers-docs\examples\chat\server\finish\src\services\message\hooks\index.js:11
const restrictToSenderOrServer = when(isProvider('external'), restrictToSender());
                                 ^

ReferenceError: when is not defined
    at Object.<anonymous> (c:\Projects\research\feathers-docs\examples\chat\server\finish\src\services\message\hooks\index.js:11:34)
    at Module._compile (module.js:571:32)
    at Object.Module._extensions..js (module.js:580:10)
    at Module.load (module.js:488:32)
    at tryModuleLoad (module.js:447:12)
    at Function.Module._load (module.js:439:3)
    at Module.require (module.js:498:17)
    at require (internal/module.js:20:19)
    at Object.<anonymous> (c:\Projects\research\feathers-docs\examples\chat\server\finish\src\services\message\index.js:6:15)
    at Module._compile (module.js:571:32)
```
## Environment:
```
node: v7.8.0
npm: 5.3.0
yarn: 0.27.5
os: Win7 x64
```

**Comment by daffl** [comment]
Reinstalling should normally help. I noticed some intermittent issues with npm as well but it didn't seem to be Feathers related and not happening anymore. Closing.
